services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=agendapet'
      - 'MYSQL_PASSWORD=${DATASOURCE_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DATASOURCE_PASSWORD}'
      - 'MYSQL_USER=${DATASOURCE_USER}''
    ports:
      - '3306'
